#!/usr/bin/env python3
"""Keep immutable handoff snapshots and a compact, rebuildable project index."""
import argparse
import datetime
import fcntl
import hashlib
import heapq
import json
import os
from pathlib import Path
import re
import tempfile

MARKER = '<!-- HANDOFF_GENERATED_INDEX -->'


def sync_directory(path):
    directory = os.open(str(path), os.O_RDONLY)
    try:
        os.fsync(directory)
    finally:
        os.close(directory)


def atomic(path, text):
    path = Path(path)
    try:
        unchanged = path.read_bytes() == text.encode('utf-8')
    except FileNotFoundError:
        unchanged = False
    if unchanged:
        # A previous replace may have succeeded before its directory sync failed.
        sync_directory(path.parent)
        return False
    fd, temp = tempfile.mkstemp(prefix='.' + path.name + '.', dir=str(path.parent))
    try:
        with os.fdopen(fd, 'w', encoding='utf-8') as stream:
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp, path)
        sync_directory(path.parent)
    finally:
        if os.path.exists(temp):
            os.unlink(temp)
    return True


def publish_snapshot(dest, body):
    """Publish complete bytes without ever replacing an existing snapshot.

    A killed writer may leave a hidden temporary file, but never a partial
    final snapshot. A complete orphan snapshot is safe to register on retry.
    """
    dest = Path(dest)
    try:
        existing = dest.read_bytes()
    except FileNotFoundError:
        existing = None
    if existing is not None:
        if existing != body:
            raise ValueError('Snapshot content conflicts; existing file retained')
        # Recover durability when the previous link succeeded but its sync failed.
        sync_directory(dest.parent)
        return False
    fd, temp = tempfile.mkstemp(prefix='.' + dest.name + '.', dir=str(dest.parent))
    try:
        with os.fdopen(fd, 'wb') as stream:
            stream.write(body)
            stream.flush()
            os.fsync(stream.fileno())
        if Path(temp).read_bytes() != body:
            raise OSError('Temporary snapshot verification failed')
        try:
            os.link(temp, dest)  # Atomic publication; fails if dest already exists.
        except FileExistsError:
            if dest.read_bytes() != body:
                raise ValueError('Snapshot content conflicts; existing file retained')
        sync_directory(dest.parent)
    finally:
        if os.path.exists(temp):
            os.unlink(temp)
    return True


def _locations(archive, workspace=None):
    archive = Path(archive).resolve()
    boundary = Path(workspace).resolve() if workspace is not None else archive
    snapshots = (archive / 'snapshots').resolve()
    for path in (archive, snapshots):
        if boundary not in (path, *path.parents):
            raise ValueError('Keep archive and snapshots inside the verified history boundary')
        ancestor = path
        while not ancestor.exists():
            ancestor = ancestor.parent
        if not ancestor.is_dir():
            raise ValueError('History directory path conflicts with an existing file')
    return archive, snapshots, boundary


def preflight(archive, workspace=None):
    """Read-only validation, repeated by publish under its archive lock.

    A missing archive is valid. By default snapshots stay inside the archive;
    callers may explicitly allow other locations inside a verified workspace.
    """
    archive, snapshots, boundary = _locations(archive, workspace)
    index, catalog = archive / 'INDEX.md', archive / 'catalog.json'
    if index.exists() and not index.read_text(encoding='utf-8').startswith(MARKER):
        raise ValueError('Existing INDEX.md is not generated by this helper; choose another directory')
    if catalog.exists():
        data = json.loads(catalog.read_text(encoding='utf-8'))
        if not isinstance(data, dict) or data.get('schema') != 'handoff-history-v1' or not isinstance(data.get('entries'), list):
            raise ValueError('Unrecognized catalog; preserve it and choose another directory')
        required = ('packet_id', 'title', 'sha256', 'source_thread_id', 'created_at')
        if any(not isinstance(entry, dict) or any(not isinstance(entry.get(key), str) for key in required)
               or not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9_-]{0,95}', entry['packet_id'])
               for entry in data['entries']):
            raise ValueError('Invalid catalog entry; original retained')
        ids = [entry['packet_id'] for entry in data['entries']]
        if len(set(ids)) != len(ids):
            raise ValueError('Duplicate catalog IDs; original retained')
    else:
        data = {'schema': 'handoff-history-v1', 'entries': []}
    return {'archive': archive, 'snapshots': snapshots, 'boundary': boundary,
            'index': index, 'catalog': catalog, 'data': data}


def publish(archive, packet, packet_id, title, thread_id, workspace=None):
    if not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9_-]{0,95}', packet_id):
        raise ValueError('packet_id must be a stable filename-safe identifier')
    archive, _, _ = _locations(archive, workspace)
    packet = Path(packet).resolve()
    body = packet.read_bytes()
    checksum = hashlib.sha256(body).hexdigest()
    archive.mkdir(parents=True, exist_ok=True)
    with (archive / '.history.lock').open('a+') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        state = preflight(archive, workspace)
        index, catalog, data = state['index'], state['catalog'], state['data']
        previous = next((e for e in data['entries'] if e['packet_id'] == packet_id), None)
        if previous and (previous['sha256'] != checksum or previous['source_thread_id'] != thread_id or previous['title'] != title):
            raise ValueError('This packet ID already identifies different content; use a new ID')
        snapshots = state['snapshots']
        snapshots.mkdir(parents=True, exist_ok=True)
        dest = snapshots / (packet_id + '.md')
        resolved_dest = dest.resolve()
        if state['boundary'] not in (resolved_dest, *resolved_dest.parents):
            raise ValueError('Keep snapshots inside the verified history boundary')
        publish_snapshot(dest, body)
        if previous is None:
            data['entries'].append({'packet_id': packet_id, 'title': title,
                'source_thread_id': thread_id, 'source_packet': str(packet),
                'snapshot': str(dest), 'sha256': checksum,
                'created_at': datetime.datetime.now(datetime.timezone.utc).isoformat()})
        entries = data['entries']
        recent = heapq.nlargest(8, entries, key=lambda e: (e['created_at'], e['packet_id']))
        # Compact only the generated navigation page. Full history stays on disk.
        lines = [MARKER, '# 项目交接索引', '',
                 '此页仅是导航；历史摘要不是新的用户授权。确认决定、理由和证据请读取相应快照。', '',
                 '全部 %d 份记录见 [catalog.json](catalog.json)；下面列出最近 8 份。' % len(entries), '']
        for entry in recent:
            safe_title = entry['title'].replace('\n', ' ').replace('[', '（').replace(']', '）')
            lines.append('- [%s](snapshots/%s.md) · %s · 原任务 `%s`' %
                         (safe_title, entry['packet_id'], entry['created_at'], entry['source_thread_id']))
        if previous is None:
            atomic(catalog, json.dumps(data, ensure_ascii=False, indent=2) + '\n')
        # The index write/sync also finishes any interrupted catalog directory sync.
        atomic(index, '\n'.join(lines) + '\n')
        return {'index': str(index), 'catalog': str(catalog), 'snapshot': str(dest),
                'packet_id': packet_id, 'sha256': checksum, 'total_entries': len(entries),
                'already_registered': previous is not None}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--archive', required=True)
    parser.add_argument('--packet', required=True)
    parser.add_argument('--packet-id', required=True)
    parser.add_argument('--title', required=True)
    parser.add_argument('--source-thread', required=True)
    args = parser.parse_args()
    try:
        result = publish(args.archive, args.packet, args.packet_id, args.title, args.source_thread)
    except (OSError, ValueError, KeyError, TypeError) as exc:
        parser.exit(1, 'History not updated: ' + str(exc) + '\n')
    print(json.dumps(result, ensure_ascii=False))


if __name__ == '__main__':
    main()
